[package]
name = "godot_rustortion"
version = "0.1.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
arc-swap = "1.8"
godot = { git = "https://github.com/godot-rust/gdext", tag = "v0.5.1", features = ["api-4-5", "experimental-threads"] }
rustortion-core = { path = "rustortion/rustortion-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
